### PR TITLE
Added external tool create and edit methods

### PR DESCRIPTION
**Pull request by atreadwell**

### CODE REVIEW

**Comment by wickning1** [comment]
externaltool.ts should be added to interfaces/index.ts

**Comment by wickning1** [comment]
The payload seems to be entirely optional. If Canvas requires fields I'd prefer the payload type matches that.

**Comment by atreadwell** [comment]
The payload fields are identical for updating and creation. For updating, all of the fields are optional. For creation, 4 of the fields are required. Would you rather I create a separate payload for creation with the only difference being 4 of the existing fields will be required?

**Comment by wickning1** [comment]
Hmm, yes I think so. It should be easy to construct with `Partial`, e.g. `type ExternalToolEditPayload = Partial<ExternalToolPayload>`. `Partial` is built in to typescript and turns every property optional.

**Comment by atreadwell** [comment]
Oh nice! Great tip. New push coming soon!

**Review by wickning1 — APPROVED** [review]

**Pull request merged**
